"""stage2: hot_event, evidence, daily_report, topics, briefs, job

Revision ID: 1f03e49cac6b
Revises: 40432d8acbdb
Create Date: 2026-08-19 19:43:32.833572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f03e49cac6b'
down_revision: Union[str, None] = '40432d8acbdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', name='report_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_date')
    )
    op.create_table('hot_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('credibility_label', sa.Enum('official', 'multi_source', 'early_signal', name='credibility_label'), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('actionability_score', sa.Integer(), nullable=False),
    sa.Column('freshness_score', sa.Integer(), nullable=False),
    sa.Column('sort_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'selected', 'brief', 'archived', name='event_status'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('extract_events', 'generate_report', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='job_status'), nullable=False),
    sa.Column('result_ref', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hot_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('hot_event_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hot_event_id'], ['hot_event.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hot_brief_report_id'), 'hot_brief', ['report_id'], unique=False)
    op.create_table('topic_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('hot_event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('what_happened', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('visual', sa.Text(), nullable=False),
    sa.Column('time_window', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hot_event_id'], ['hot_event.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['daily_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_recommendation_report_id'), 'topic_recommendation', ['report_id'], unique=False)
    op.create_table('event_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hot_event_id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hot_event_id'], ['hot_event.id'], ),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_item_id', name='uq_event_evidence_source_item')
    )
    op.create_index(op.f('ix_event_evidence_hot_event_id'), 'event_evidence', ['hot_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_evidence_hot_event_id'), table_name='event_evidence')
    op.drop_table('event_evidence')
    op.drop_index(op.f('ix_topic_recommendation_report_id'), table_name='topic_recommendation')
    op.drop_table('topic_recommendation')
    op.drop_index(op.f('ix_hot_brief_report_id'), table_name='hot_brief')
    op.drop_table('hot_brief')
    op.drop_table('job')
    op.drop_table('hot_event')
    op.drop_table('daily_report')
    # ### end Alembic commands ###
