"""stage4: user, invite_code, creator_profile, personalized_report/topic, job.context

Revision ID: 361dc60259d6
Revises: 1f03e49cac6b
Create Date: 2026-08-19 22:52:50.105534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '361dc60259d6'
down_revision: Union[str, None] = '1f03e49cac6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('creator_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('positioning', sa.Text(), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('video_length', sa.Text(), nullable=False),
    sa.Column('forbidden', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('invite_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['used_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_code_code'), 'invite_code', ['code'], unique=True)
    op.create_table('personalized_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalized_report_user_id'), 'personalized_report', ['user_id'], unique=False)
    op.create_table('personalized_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('hot_event_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('what_happened', sa.Text(), nullable=False),
    sa.Column('why_now', sa.Text(), nullable=False),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('hook', sa.Text(), nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('visual', sa.Text(), nullable=False),
    sa.Column('time_window', sa.Text(), nullable=False),
    sa.Column('recommendation_reason', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hot_event_id'], ['hot_event.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['personalized_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalized_topic_report_id'), 'personalized_topic', ['report_id'], unique=False)
    op.add_column('job', sa.Column('context', sa.JSON(), nullable=True))
    with op.batch_alter_table('job') as batch_op:
        batch_op.alter_column(
            'kind',
            existing_type=sa.VARCHAR(length=15),
            type_=sa.Enum('extract_events', 'generate_report', 'personalized_report', name='job_kind'),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job') as batch_op:
        batch_op.alter_column(
            'kind',
            existing_type=sa.Enum('extract_events', 'generate_report', 'personalized_report', name='job_kind'),
            type_=sa.VARCHAR(length=15),
            existing_nullable=False,
        )
    op.drop_column('job', 'context')
    op.drop_index(op.f('ix_personalized_topic_report_id'), table_name='personalized_topic')
    op.drop_table('personalized_topic')
    op.drop_index(op.f('ix_personalized_report_user_id'), table_name='personalized_report')
    op.drop_table('personalized_report')
    op.drop_index(op.f('ix_invite_code_code'), table_name='invite_code')
    op.drop_table('invite_code')
    op.drop_table('creator_profile')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
