"""initial schema: source, source_item, collection_run

Revision ID: 40432d8acbdb
Revises: 
Create Date: 2026-08-19 19:11:53.887173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40432d8acbdb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('rss', 'github_releases', 'x', name='source_type'), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credibility_level', sa.Enum('official', 'media', name='credibility_level'), nullable=False),
    sa.Column('max_items_per_day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='collection_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('items_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_run_source_id'), 'collection_run', ['source_id'], unique=False)
    op.create_table('source_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_item_source_id'), 'source_item', ['source_id'], unique=False)
    op.create_index(op.f('ix_source_item_url_hash'), 'source_item', ['url_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_item_url_hash'), table_name='source_item')
    op.drop_index(op.f('ix_source_item_source_id'), table_name='source_item')
    op.drop_table('source_item')
    op.drop_index(op.f('ix_collection_run_source_id'), table_name='collection_run')
    op.drop_table('collection_run')
    op.drop_table('source')
    # ### end Alembic commands ###
