"""stage6: topic_recommendation.reviewed

Revision ID: 7c4b0e07469b
Revises: b3978d2b230e
Create Date: 2026-08-20 10:39:07.079572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4b0e07469b'
down_revision: Union[str, None] = 'b3978d2b230e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic_recommendation', sa.Column('reviewed', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topic_recommendation', 'reviewed')
    # ### end Alembic commands ###
