"""stage5: creation_plan, topic_feedback, mail_delivery, subscription

Revision ID: b3978d2b230e
Revises: 361dc60259d6
Create Date: 2026-08-20 00:55:05.904308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3978d2b230e'
down_revision: Union[str, None] = '361dc60259d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('price_type', sa.Enum('founding', 'standard', name='price_type'), nullable=False),
    sa.Column('monthly_price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', name='subscription_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('mail_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='mail_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['personalized_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mail_delivery_user_id'), 'mail_delivery', ['user_id'], unique=False)
    op.create_table('creation_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('core_viewpoint', sa.Text(), nullable=False),
    sa.Column('hooks', sa.JSON(), nullable=True),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('visual', sa.Text(), nullable=False),
    sa.Column('titles', sa.JSON(), nullable=True),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['personalized_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_index(op.f('ix_creation_plan_user_id'), 'creation_plan', ['user_id'], unique=False)
    op.create_table('topic_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('want', 'not_interested', 'published', name='feedback_status'), nullable=False),
    sa.Column('douyin_url', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['personalized_topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_id', name='uq_feedback_user_topic')
    )
    op.create_index(op.f('ix_topic_feedback_user_id'), 'topic_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_feedback_user_id'), table_name='topic_feedback')
    op.drop_table('topic_feedback')
    op.drop_index(op.f('ix_creation_plan_user_id'), table_name='creation_plan')
    op.drop_table('creation_plan')
    op.drop_index(op.f('ix_mail_delivery_user_id'), table_name='mail_delivery')
    op.drop_table('mail_delivery')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_table('subscription')
    # ### end Alembic commands ###
